config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  resources :publications
  root 'articles#index'
  devise_for :users
  resources :comments
  resources :articles
  resources :users, only: %i[index show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  extend FriendlyId
  # Sets the default find finder to slugged but defaults if not found to default finders like ID
  friendly_id :uuid, use: %i[slugged finders]

  belongs_to :publication
  has_and_belongs_to_many :users, distinct: true

  validates :name, presence: true
  validates :publication_id, presence: true
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.paginate(page: params[:page], per_page: params[:per_page] ||= 30).order(created_at: :desc)
    respond_to do |format|
      format.json { render json: Publication.all, status: :ok }
      format.html {}
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    respond_to do |format|
      format.json { render json: @publication }
      format.html { @publication }
    end
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      begin
        @subscription = Subscription.friendly.find(params[:id])
      rescue StandardError
        respond_to do |format|
          format.json { render status: 404, json: { alert: "The publication you're looking for cannot be found" } }
          format.html { redirect_to articles_path, alert: "The publication you're looking for cannot be found" }
        end
      end
      if @subscription.present?
         @subscription # Pass in Model object
      end
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:name, :publication_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :subscription_name %>
  </div>

  <div class="field">
    <%= form.collection_select :publication_id, Publication.all, :id, :companyname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>Editing Subscription</h1>

    <%= render 'form', subscription: @subscription %>

    <%= link_to 'Show', @subscription %> |
    <%= link_to 'Back', subscriptions_path %>
  </div>
</div>

app/views/subscriptions/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Subscriptions</h1>
        <%= will_paginate @subscriptions %>
      </div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @subscriptions.each do |subscription| %>
            <tr>
              <td><%= subscription.name %></td>
              <td><%= link_to 'Show', subscription %></td>
              <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
              <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

<br>

      <div class="panel-footer">
        <%= link_to 'New Subscription', new_subscription_path, class: 'btn btn-success'%>
        <%= page_entries_info @subscriptions %>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>New Subscription</h1>

    <%= render 'form', subscription: @subscription %>

    <%= link_to 'Back', subscriptions_path %>
  </div>
</div>

app/views/subscriptions/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-success">
      <div class="panel-heading">
        Subscription
      </div>

      <div class="panel-body">
        <p>
          <strong>Name:</strong>
          <%= @subscription.name %>
        </p>
      </div>

      <div class="panel-footer">
        <%= link_to 'Edit', edit_subscription_path(@subscription) %> |
        <%= link_to 'Back', subscriptions_path %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h1>Users Subscribed</h1>
      </div>

      <table class="table table-hover">
        <thead>
        <tr>
          <th>Title</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @subscription.users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <% if policy(user).show? %>
              <td><%= link_to 'Show', user %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>